# Introduzione a Python e NumPy
## 1. Fondamenti di Python
Python è un linguaggio di programmazione di alto livello noto per la sua semplicità e leggibilità. È ampiamente utilizzato in diversi ambiti, tra cui l'analisi dei dati, l'apprendimento automatico e il calcolo scientifico. In questa sezione, copriremo alcuni concetti di base di Python.

Variabili e tipi di dati
In Python, puoi assegnare valori alle variabili utilizzando l'operatore di assegnazione (=). Python supporta vari tipi di dati, come interi, float, stringhe, booleani e altro ancora.


Per eseguire le celle: Shift + Invio


PS: Non spaventarti se nel corso di questo  tutorial vedi tante funzioni. Non sono da imparare a memoria,  però l'importante è sapere che esistono funzioni già implementate che svolgono compiti anche complessi!

In [ ]:
# Variabile intera
x = 10

# Variabile float
y = 3.14

# Variabile stringa
nome = "Mario Rossi"

# Variabile booleana
its_true = True

## Liste e indicizzazione
Le liste sono collezioni ordinate di elementi. Puoi definire una lista racchiudendo gli elementi tra parentesi quadre ([]). Python utilizza l'indicizzazione basata su zero per accedere agli elementi in una lista.

In [ ]:
# Lista di numeri
numeri = [1, 2, 3, 4, 5]

# Accesso agli elementi
print(numeri[0])  # Output: 1
print(numeri[2])  # Output: 3

# Estrarre una porzione di lista
print(numeri[1:4])  # Output: [2, 3, 4]

1
3
[2, 3, 4]


## Istruzioni di controllo del flusso
Python fornisce istruzioni di controllo del flusso come if, for e while per controllare l'esecuzione del codice in base a determinate condizioni.

In [ ]:
# Istruzione if
x = 10
if x > 5:
    print("x è maggiore di 5")
else:
    print("x è minore o uguale a 5")

# Ciclo for
frutta = ["mela", "banana", "ciliegia"]
for frutto in frutta:
    print(frutto)

# Ciclo while
i = 0
while i < 5:
    print(i)
    i += 1

x è maggiore di 5
mela
banana
ciliegia
0
1
2
3
4


# 2. Concetti di base di NumPy
NumPy (Numerical Python) è una potente libreria per il calcolo scientifico in Python. Fornisce efficienti oggetti di matrici multidimensionali e una vasta gamma di funzioni matematiche. Esploriamo alcuni dei suoi concetti di base.

## Installazione
Se non hai ancora installato NumPy, puoi farlo utilizzando pip:

! pip install numpy #non è necessario farlo qui perchè è già installato. Con il ! si indica un comando da passare al terminale e quindi da interpretare non con python


## Importazione di NumPy
Per utilizzare NumPy nel tuo codice Python, è necessario importarlo:

In [ ]:
import numpy as np

#as indica l'alias con cui vuoi chiamare facilmente numpy - lo vedrai spesso

## Array NumPy
Gli array NumPy sono simili alle liste, ma sono più efficienti per gestire grandi quantità di dati. Possono avere più dimensioni, come array 1D, array 2D, e così via.



In [ ]:
# Array 1D
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

# Array 2D
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


## Attributi degli array
Gli array NumPy hanno diversi attributi che forniscono informazioni sulla loro forma, dimensione e tipo di dati.


In [ ]:
arr = np.array([1, 2, 3, 4, 5])

print("Forma:", arr.shape)
print("Dimensione:", arr.size)
print("Tipo di dati:", arr.dtype)

Forma: (5,)
Dimensione: 5
Tipo di dati: int64


## Operazioni sugli array
NumPy fornisce varie operazioni matematiche che possono essere applicate agli array, come operazioni elemento per elemento, operazioni matriciali e funzioni statistiche.

In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Operazioni elemento per elemento
print(arr1 + arr2)  # Output: [5, 7, 9]
print(arr1 * arr2)  # Output: [4, 10, 18]

# Prodotto matriciale
result = np.dot(arr1, arr2)
print(result)  # Output: 32

# Funzioni statistiche
print(np.mean(arr1))  # Output: 2.0
print(np.max(arr2))  # Output: 6

[5 7 9]
[ 4 10 18]
32
2.0
6


## Calcolare la media, la deviazione standard e altre statistiche
NumPy fornisce diverse funzioni per calcolare statistiche di base sugli array.

In [ ]:
arr = np.array([1, 2, 3, 4, 5])

# Calcolare la media
mean = np.mean(arr)
print("Media:", mean)  # Output: 3.0

# Calcolare la deviazione standard
std = np.std(arr)
print("Deviazione standard:", std)  # Output: 1.4142135623730951

# Calcolare la varianza
var = np.var(arr)
print("Varianza:", var)  # Output: 2.0

# Calcolare il valore massimo
max_value = np.max(arr)
print("Valore massimo:", max_value)  # Output: 5

# Calcolare il valore minimo
min_value = np.min(arr)
print("Valore minimo:", min_value)  # Output: 1

# Calcolare la somma degli elementi
sum_value = np.sum(arr)
print("Somma degli elementi:", sum_value)  # Output: 15

Media: 3.0
Deviazione standard: 1.4142135623730951
Varianza: 2.0
Valore massimo: 5
Valore minimo: 1
Somma degli elementi: 15


In [ ]:
arr = np.array([1, 2, 3, 4, 5])

# Esempio di operazioni matematiche
squared = np.square(arr)  # Eleva al quadrato ogni elemento
print("Al quadrato:", squared)  # Output: [ 1,  4,  9, 16, 25]

square_root = np.sqrt(arr)  # Calcola la radice quadrata di ogni elemento
print("Radice quadrata:", square_root)  # Output: [1.        , 1.41421356, 1.73205081, 2.        , 2.23606798]

exponential = np.exp(arr)  # Calcola l'esponenziale di ogni elemento
print("Esponenziale:", exponential)  # Output: [  2.71828183,   7.3890561 ,  20.08553692,  54.59815003, 148.4131591 ]

# Operazioni su array multidimensionali
arr2d = np.array([[1, 2], [3, 4]])

# Somma di tutti gli elementi dell'array
sum_all = np.sum(arr2d)
print("Somma totale:", sum_all)  # Output: 10

# Somma per colonne
sum_cols = np.sum(arr2d, axis=0)
print("Somma per colonne:", sum_cols)  # Output: [4, 6]

# Somma per righe
sum_rows = np.sum(arr2d, axis=1)
print("Somma per righe:", sum_rows)  # Output: [3, 7]

Al quadrato: [ 1  4  9 16 25]
Radice quadrata: [1.         1.41421356 1.73205081 2.         2.23606798]
Esponenziale: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Somma totale: 10
Somma per colonne: [4 6]
Somma per righe: [3 7]


Altre funzioni piu complesse di numpy (Vedi l'ultima che sarà fondamentale)

In [ ]:
# Creare un array di valori casuali
random_array = np.random.rand(3, 3)
print("Array casuale:")
print(random_array)

# Trasporre un array
transposed_array = np.transpose(random_array)
print("Array trasposto:")
print(transposed_array)

# Calcolare il prodotto di matrici
matrix1 = np.random.rand(2, 3)
matrix2 = np.random.rand(3, 4)
matrix_product = np.dot(matrix1, matrix2)
print("Prodotto di matrici:")
print(matrix_product)

# Calcolare l'inversa di una matrice
matrix = np.array([[1, 2], [3, 4]])
inverse_matrix = np.linalg.inv(matrix)
print("Matrice inversa:")
print(inverse_matrix)

# Risolvere un sistema lineare
A = np.array([[2, 1], [1, 3]])
b = np.array([3, 5])
solution = np.linalg.solve(A, b)
print("Soluzione del sistema lineare:")
print(solution)

# Calcolare autovalori e autovettori di una matrice
matrix = np.array([[4, -2], [1, 3]])
eigenvalues, eigenvectors = np.linalg.eig(matrix)
print("Autovalori:")
print(eigenvalues)
print("Autovettori:")
print(eigenvectors)

# Applicare una funzione a tutti gli elementi di un array
arr = np.array([-1, 2, -3, 4, -5])
abs_values = np.abs(arr)
print("Valori assoluti:")
print(abs_values)

# Filtrare gli elementi di un array basato su una condizione
filtered_values = arr[arr > 0]
print("Valori positivi:")
print(filtered_values)

Array casuale:
[[0.8813265  0.51872064 0.39091731]
 [0.9517091  0.11727642 0.56585067]
 [0.14342947 0.88666988 0.65410212]]
Array trasposto:
[[0.8813265  0.9517091  0.14342947]
 [0.51872064 0.11727642 0.88666988]
 [0.39091731 0.56585067 0.65410212]]
Prodotto di matrici:
[[0.23917663 0.22671366 0.55474175 0.57789049]
 [0.81096422 0.44208614 1.39575869 1.42592885]]
Matrice inversa:
[[-2.   1. ]
 [ 1.5 -0.5]]
Soluzione del sistema lineare:
[0.8 1.4]
Autovalori:
[3.5+1.32287566j 3.5-1.32287566j]
Autovettori:
[[0.81649658+0.j         0.81649658-0.j        ]
 [0.20412415-0.54006172j 0.20412415+0.54006172j]]
Valori assoluti:
[1 2 3 4 5]
Valori positivi:
[2 4]


Sempre sul  filtrare  i valori: 

In [ ]:

# Creare un array casuale
random_array = np.random.randint(-10, 10, size=(5, 5))
print("Array casuale:")
print(random_array)

# Filtrare gli elementi negativi
negative_values = random_array[random_array < 0]
print("Valori negativi:")
print(negative_values)

# Filtrare gli elementi pari
even_values = random_array[random_array % 2 == 0]
print("Valori pari:")
print(even_values)

# Filtrare gli elementi basati su una condizione complessa
filtered_values = random_array[(random_array % 2 == 0) & (random_array > 0)]
print("Valori pari e positivi:")
print(filtered_values)

# Sostituire gli elementi filtrati con un nuovo valore
random_array[random_array < 0] = 0
print("Array con valori negativi sostituiti:")
print(random_array)

Array casuale:
[[  2  -6  -7  -1  -2]
 [ -6 -10   8   5   1]
 [  6  -2  -2   9  -2]
 [  3  -9  -3  -7  -6]
 [ -2   1  -3  -2 -10]]
Valori negativi:
[ -6  -7  -1  -2  -6 -10  -2  -2  -2  -9  -3  -7  -6  -2  -3  -2 -10]
Valori pari:
[  2  -6  -2  -6 -10   8   6  -2  -2  -2  -6  -2  -2 -10]
Valori pari e positivi:
[2 8 6]
Array con valori negativi sostituiti:
[[2 0 0 0 0]
 [0 0 8 5 1]
 [6 0 0 9 0]
 [3 0 0 0 0]
 [0 1 0 0 0]]
